/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/play/[provider]/[videoId]/[episode]': RouteRecordInfo<'/play/[provider]/[videoId]/[episode]', '/play/:provider/:videoId/:episode', { provider: ParamValue<true>, videoId: ParamValue<true>, episode: ParamValue<true> }, { provider: ParamValue<false>, videoId: ParamValue<false>, episode: ParamValue<false> }>,
    '/search/[provider]/[page]': RouteRecordInfo<'/search/[provider]/[page]', '/search/:provider/:page', { provider: ParamValue<true>, page: ParamValue<true> }, { provider: ParamValue<false>, page: ParamValue<false> }>,
  }
}
